### ISSUE TITLE
ksoftseq immediately aborts replay on opening a USB drive view via WPS

### ISSUE THREAD

**Issue by lerdmann** [komh/ksoftseq#13] opened 2023-09-15 19:14 UTC
When I play a MIDI file via UNIAUD and if I open a USB drive via the WPS, then the sound immediately stops.
When I play a MIDI file via USB audio and if I open a USB drive via the WPS, then I get a short hiccup but the sound will continue to play.

I suspected a problem in the USB drivers so I replaced all kernel spinlocks (which will unfortunately disable interrupts for the time where they are acquired) with my own spinlock implementation (that will not disable interrupts). I did this for the USB HC driver (USBEHCD.SYS) and also the MSD class driver (USBMSD.ADD) which are the two drivers that would have a bearing on this problem. That did not make any difference but then I noted the following:

When I play a WAV or a MP3 file via UNIAUD and if I open a USB drive via the WPS, the sound will continue to play undisturbed.
When I play a WAV or a MP3 file via USB audio and if I open a USB drive via the WPS, the sound will continue to play undisturbed. 

The hiccup also occured with USB audio if while replaying a MIDI file I opened the drive view of any drive object via the WPS (also for drives that are managed by OS2AHCI.ADD), so it could not only be a USB problem.

It looks like the threads that ksoftseq uses to play sound or receive notifications do not (all) have a sufficiently high priority. The WPS threads (PMSHELL.EXE) seem to interfere, in particular if a drive view is opened for the first time. At least that is my suspicion.

**Comment by lerdmann** [comment] 2023-09-16 06:04
I did a further check: I limited the amount of logical processors to 1 (/MAXCPU=1 for ACPI.PSD). That much improved the situation, the sound will no longer be completely interrupted when I open a drive object via the WPS. Looks like the SMP implementation on OS/2 has a problem.
But I still think that this problem can be circumvented if the track priority of the playing thread and/or notifiying thread would be increased.

**Comment by komh** [comment] 2023-09-18 11:10
For a priority, you can add 'set KAI_TIMECRITICAL=1' to config.sys.

And would you mind testing this with kmidi? I want to know whether the problem is in kai or in ksoftseq.

Thanks!

**Comment by lerdmann** [comment] 2023-09-19 23:12
Using UNIAUD: setting KAI_TIMECRITICAL=1 did not help. The sound still stops immediately. The same happens when I use kmidi (I had KAI_TIMECRITICAL also set): it starts playing, with the TMSF timestamp increasing with playing time, when I then open either a USB drive or a FTP connection managed via the NDFS plugin (that one is known to notoriously block the WPS for extended lengths of time and really, it`s a flaw of the WPS and not of the NDFS plugin), the sound will immediately stop to play.
With USB Audio, things are better (as has also been before): only a short hiccup, but things will continue to play.

**Comment by komh** [comment] 2023-09-21 12:34
How about using ```priority``` utility like this which controls priorities of a child program:

```priority 3 31 kmidi midi-file.mid sound-font.sf2```

I attach priority utility for the case that you don't have it.

[priority.zip](https://github.com/komh/ksoftseq/files/12684423/priority.zip)

And if you have ```fluidsynth```, could you test it, too ? It uses DART APIs directly not though libkai. So I can determine the problem is in internal logic of libkai or in DART itself.

Thanks for your help!

**Comment by lerdmann** [comment] 2023-09-28 17:30
priority.exe did not help, kmidi will stop when opening a USB drive object. fluidsynth will lead to the same problem, regardless if run standalone or called via "priority.exe".
Again, USBAUDIO.SYS / USBAUD2.SYS do a much better job than UNIAUD16/32.SYS.
USB audio devices continue to play with close to no hiccup.
I am beginning to believe this cannot be fixed in ksoftseq or fluidsynth but only in the audio driver :-(

**Comment by komh** [comment] 2023-10-02 13:37
I agree.

Finally, could you test kmidi with setting KAI_AUTOMODE=UNIAUD ?

**Comment by lerdmann** [comment] 2023-10-02 15:48
Ha, that helped ! There is a short hiccup, comparable to what happens with the USB audio drivers (a bit worse ...), but it will continue to play.

**Comment by lerdmann** [comment] 2023-10-02 16:09
By, the way, in kai, "kai_dart.c", in routine "dartChNum", I see this:

    {
        ulChannels = 4; // failed. try 4 channels
        MixSetupParms.ulChannels = ulChannels;
        if( mciSendCommand( AmpOpenParms.usDeviceID,
                            MCI_MIXSETUP, MCI_WAIT | MCI_MIXSETUP_INIT,
                            ( PVOID )&MixSetupParms, 0 ))
            ulChannels = 2; // failed again...so, drivers support only 2 channels
    }

There is no reattempt to call MCI_MIXSETUP if channels = 2 (and that it the best it will ever get with any sound driver ...).
Don`t you need to reattempt MCI_MIXSETUP with MixSetupParms.ulChannels = 2 ????

And if not, and if you were successful with 6 or 4 channels, don't you at least need to call MCI_MIXSETUP,MCI_WAIT | MICSETUP_DEINIT to uninitialize the mix setup ? Same holds true for DartClose.

**Comment by komh** [comment] 2023-10-03 08:40
> By, the way, in kai, "kai_dart.c", in routine "dartChNum", I see this:
> 
> ```
> {
>     ulChannels = 4; // failed. try 4 channels
>     MixSetupParms.ulChannels = ulChannels;
>     if( mciSendCommand( AmpOpenParms.usDeviceID,
>                         MCI_MIXSETUP, MCI_WAIT | MCI_MIXSETUP_INIT,
>                         ( PVOID )&MixSetupParms, 0 ))
>         ulChannels = 2; // failed again...so, drivers support only 2 channels
> }
> ```
> 
> There is no reattempt to call MCI_MIXSETUP if channels = 2 (and that it the best it will ever get with any sound driver ...). Don`t you need to reattempt MCI_MIXSETUP with MixSetupParms.ulChannels = 2 ????
> 

2 channels are minimum. I don't think there are any sound cards and drivers do not support 2 channels at least, nowadays.

> And if not, and if you were successful with 6 or 4 channels, don't you at least need to call MCI_MIXSETUP,MCI_WAIT | MICSETUP_DEINIT to uninitialize the mix setup ? Same holds true for DartClose.

MCI_CLOSE will do it.

**Comment by komh** [comment] 2023-10-03 09:01
I attach a new kmidi whose audio buffer size is enlarged. Could you test this whether or not it helps ?

[kmidi.zip](https://github.com/komh/ksoftseq/files/12790660/kmidi.zip)

**Comment by lerdmann** [comment] 2023-10-05 23:04
Unfortunately, same result

**Comment by komh** [comment] 2023-10-08 10:50
Too bad. Audio drivers should fix this problem.

 I'll close this ticket as invalid.

Thanks!

**Closed as completed by komh** 2023-10-08 10:50 UTC
Labels: invalid
